package account

import (
	"context"
	"fmt"
	"time"

	"email-campaign-system/internal/models"
	"email-campaign-system/internal/storage/repository"
)

// Manager handles account business logic.
// All persistence is delegated to the injected repository.
type Manager struct {
	repo *repository.AccountRepository
}

func NewManager(repo *repository.AccountRepository) *Manager {
	return &Manager{repo: repo}
}

// ─── Request / Option types ──────────────────────────────────────────────────

type CreateRequest struct {
	Email         string
	Provider      string
	Password      string
	AppPassword   string
	OAuthToken    string
	SenderName    string
	DailyLimit    int
	RotationLimit int
	ProxyID       *string // UUID string
	SMTPHost      string
	SMTPPort      int
	UseSSL        bool
	UseTLS        bool
	Config        map[string]interface{}
}

// backend/internal/core/account/types.go

type UpdateRequest struct {
    Email         *string                // nil = "don't touch this field"
    Password      *string
    AppPassword   *string
    SenderName    *string
    DailyLimit    *int                   // nil = don't touch; 0 = remove limit
    RotationLimit *int
    ProxyID       *string
    SMTPHost      *string
    SMTPPort      *int
    UseSSL        *bool                  // nil = don't touch; false = explicitly disable
    UseTLS        *bool
    Config        map[string]interface{} // map is already nil-able, no change needed
}


type ListOptions struct {
	Provider    string
	Status      string
	IsSuspended *bool
	Page        int
	PageSize    int
	SortBy      string
	SortOrder   string
}

type LogOptions struct {
	Type     string
	Page     int
	PageSize int
}

type TestResult struct {
	ResponseTime int
	Provider     string
	ServerInfo   string
}

type Stats struct {
	ID                  string     // UUID string
	Email               string
	TotalSent           int
	TotalFailed         int
	SuccessRate         float64
	AvgResponseTime     int
	SentToday           int
	SentThisWeek        int
	SentThisMonth       int
	HealthScore         float64    // 0–100 scale
	ConsecutiveFailures int
	LastUsedAt          *time.Time // pointer — nil means never used
	DailyLimitRemaining int
	RotationRemaining   int
}

type Health struct {
    Score     float64       `json:"score"`
    Status    string        `json:"status"`
    LastCheck time.Time     `json:"last_check"`
    LastError string        `json:"last_error"`
    Uptime    time.Duration `json:"uptime_seconds"`
}


type ImportResult struct {
	Total      int      `json:"total"`
	Successful int      `json:"successful"`
	Failed     int      `json:"failed"`
	Errors     []string `json:"errors"`
}

// ─── CRUD ────────────────────────────────────────────────────────────────────

// Create inserts a new account. UUID is generated by the DB (RETURNING id).
func (m *Manager) Create(ctx context.Context, req *CreateRequest) (*models.Account, error) {
	encPass := req.Password
	if req.AppPassword != "" {
		encPass = req.AppPassword
	}

	ra := &repository.Account{
		Email:             req.Email,
		Name:              req.SenderName,
		Provider:          req.Provider,
		Status:            string(models.AccountStatusActive),
		EncryptedPassword: []byte(encPass),
		OAuthToken:        req.OAuthToken,
		SMTPHost:          req.SMTPHost,
		SMTPPort:          req.SMTPPort,
		SMTPUseTLS:        req.UseTLS,
		SMTPUseSSL:        req.UseSSL,
		DailyLimit:        req.DailyLimit,
		RotationLimit:     req.RotationLimit,
		HealthScore:       1.0,
		IsActive:          true,
		Config:            req.Config,
	}
	if req.ProxyID != nil && *req.ProxyID != "" {
		ra.ProxyID = *req.ProxyID
		ra.UseProxy = true
	}

	if err := m.repo.Create(ctx, ra); err != nil {
		return nil, fmt.Errorf("account.Create: %w", err)
	}
	return toModel(ra), nil
}

// List returns accounts matching opts together with the total row count.
func (m *Manager) List(ctx context.Context, opts *ListOptions) ([]*models.Account, int, error) {
	filter := repository.AccountFilter{
		SortBy:    opts.SortBy,
		SortOrder: opts.SortOrder,
	}
	if opts.Provider != "" {
		filter.Provider = []string{opts.Provider}
	}
	if opts.Status != "" {
		filter.Status = []string{opts.Status}
	}
	filter.IsSuspended = opts.IsSuspended
	if opts.PageSize > 0 {
		filter.Limit = opts.PageSize
		if opts.Page > 1 {
			filter.Offset = (opts.Page - 1) * opts.PageSize
		}
	}

	// FIX: repo.List takes *AccountFilter — pass address, not value
	ras, total, err := m.repo.List(ctx, &filter)
	if err != nil {
		return nil, 0, fmt.Errorf("account.List: %w", err)
	}

	accounts := make([]*models.Account, len(ras))
	for i, ra := range ras {
		accounts[i] = toModel(ra)
	}
	return accounts, total, nil
}

// GetByID fetches a single account by its UUID string.
func (m *Manager) GetByID(ctx context.Context, id string) (*models.Account, error) {
	ra, err := m.repo.GetByID(ctx, id) // repo now accepts string after Fix A
	if err != nil {
		return nil, fmt.Errorf("account.GetByID(%s): %w", id, err)
	}
	return toModel(ra), nil
}

func (m *Manager) Update(ctx context.Context, id string, req UpdateRequest) (*models.Account, error) {
    ra, err := m.repo.GetByID(ctx, id)
    if err != nil {
        return nil, fmt.Errorf("account.Update(%s): fetch: %w", id, err)
    }

    if req.Email != nil {
        ra.Email = *req.Email          // ✅ dereference
    }
    if req.Password != nil && *req.Password != "" {
        ra.EncryptedPassword = []byte(*req.Password)
    }
    if req.AppPassword != nil && *req.AppPassword != "" {
        ra.EncryptedPassword = []byte(*req.AppPassword) // app password takes precedence
    }
    if req.SenderName != nil {
        ra.Name = *req.SenderName
    }
    if req.DailyLimit != nil {
        ra.DailyLimit = *req.DailyLimit
    }
    if req.RotationLimit != nil {
        ra.RotationLimit = *req.RotationLimit
    }
    if req.SMTPHost != nil {
        ra.SMTPHost = *req.SMTPHost
    }
    if req.SMTPPort != nil {
        ra.SMTPPort = *req.SMTPPort
    }
    if req.UseSSL != nil {
        ra.SMTPUseSSL = *req.UseSSL
    }
    if req.UseTLS != nil {
        ra.SMTPUseTLS = *req.UseTLS
    }
    if req.ProxyID != nil {
        ra.ProxyID = *req.ProxyID
        ra.UseProxy = *req.ProxyID != ""
    }
    if req.Config != nil {
        ra.Config = req.Config
    }

    if err := m.repo.Update(ctx, ra); err != nil {
        return nil, fmt.Errorf("account.Update(%s): persist: %w", id, err)
    }
    return toModel(ra), nil
}

func (m *Manager) Delete(ctx context.Context, id string) error {
	if err := m.repo.Delete(ctx, id); err != nil {
		return fmt.Errorf("account.Delete(%s): %w", id, err)
	}
	return nil
}

// ─── Status management ───────────────────────────────────────────────────────

// Suspend marks the account as suspended.
func (m *Manager) Suspend(ctx context.Context, id string, reason string) (*models.Account, error) {
	ra, err := m.repo.GetByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("account.Suspend(%s): %w", id, err)
	}

	now := time.Now()
	ra.Status = string(models.AccountStatusSuspended)
	ra.IsSuspended = true
	ra.SuspensionReason = reason
	ra.SuspendedAt = &now  // FIX: ra.SuspendedAt is *time.Time — take address of now
	ra.UpdatedAt = now     // ra.UpdatedAt is time.Time — plain assignment

	if err := m.repo.Update(ctx, ra); err != nil {
		return nil, fmt.Errorf("account.Suspend(%s): persist: %w", id, err)
	}
	return toModel(ra), nil
}

// Activate re-enables a suspended or inactive account.
func (m *Manager) Activate(ctx context.Context, id string) (*models.Account, error) {
	ra, err := m.repo.GetByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("account.Activate(%s): %w", id, err)
	}

	ra.Status = string(models.AccountStatusActive)
	ra.IsSuspended = false
	ra.SuspensionReason = ""
	ra.SuspendedAt = nil   // FIX: *time.Time — clear by setting nil
	ra.IsActive = true
	ra.UpdatedAt = time.Now()

	if err := m.repo.Update(ctx, ra); err != nil {
		return nil, fmt.Errorf("account.Activate(%s): persist: %w", id, err)
	}
	return toModel(ra), nil
}

// ─── Stats & Health ──────────────────────────────────────────────────────────

// GetStats derives sending statistics from the live account row.
func (m *Manager) GetStats(ctx context.Context, id string) (*Stats, error) {
	ra, err := m.repo.GetByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("account.GetStats(%s): %w", id, err)
	}

	dailyRemaining := clampMin(ra.DailyLimit-ra.SentToday, 0)
	rotRemaining := clampMin(ra.RotationLimit-ra.SentThisRotation, 0)

	return &Stats{
		ID:                  ra.ID,         // string after Fix A
		Email:               ra.Email,
		TotalSent:           int(ra.TotalSent),
		TotalFailed:         int(ra.TotalFailed),
		SuccessRate:         ra.SuccessRate,
		SentToday:           ra.SentToday,
		HealthScore:         ra.HealthScore * 100,
		ConsecutiveFailures: ra.ConsecutiveFailures,
		LastUsedAt:          ra.LastUsedAt, // FIX: both are *time.Time — direct assignment, no &
		DailyLimitRemaining: dailyRemaining,
		RotationRemaining:   rotRemaining,
	}, nil
}

// GetHealth returns the health score (0–100) and a status label.
func (m *Manager) GetHealth(ctx context.Context, id string) (*Health, error) {
	ra, err := m.repo.GetByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("account.GetHealth(%s): %w", id, err)
	}
	score := ra.HealthScore * 100
	return &Health{Score: score, Status: healthStatusLabel(score)}, nil
}

// ─── SMTP / OAuth ────────────────────────────────────────────────────────────

// TestConnection returns SMTP server metadata for the account.
func (m *Manager) TestConnection(ctx context.Context, id string) (*TestResult, error) {
	ra, err := m.repo.GetByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("account.TestConnection(%s): %w", id, err)
	}
	return &TestResult{
		Provider:   ra.Provider,
		ServerInfo: fmt.Sprintf("%s:%d", ra.SMTPHost, ra.SMTPPort),
	}, nil
}

// RefreshOAuth persists an updated OAuth token after the exchange is done externally.
func (m *Manager) RefreshOAuth(ctx context.Context, id string) (*models.Account, error) {
	ra, err := m.repo.GetByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("account.RefreshOAuth(%s): %w", id, err)
	}
	ra.UpdatedAt = time.Now()
	if err := m.repo.Update(ctx, ra); err != nil {
		return nil, fmt.Errorf("account.RefreshOAuth(%s): persist: %w", id, err)
	}
	return toModel(ra), nil
}

// ─── Limits / Logs / Campaigns / Import ─────────────────────────────────────

// ResetLimits zeroes the daily and rotation counters.
func (m *Manager) ResetLimits(ctx context.Context, id string) error {
	ra, err := m.repo.GetByID(ctx, id)
	if err != nil {
		return fmt.Errorf("account.ResetLimits(%s): %w", id, err)
	}
	ra.SentToday = 0
	ra.SentThisRotation = 0
	ra.UpdatedAt = time.Now()
	if err := m.repo.Update(ctx, ra); err != nil {
		return fmt.Errorf("account.ResetLimits(%s): persist: %w", id, err)
	}
	return nil
}

// GetLogs returns paginated email log entries for the account.
func (m *Manager) GetLogs(ctx context.Context, id string, opts *LogOptions) ([]interface{}, int, error) {
	if _, err := m.repo.GetByID(ctx, id); err != nil {
		return nil, 0, fmt.Errorf("account.GetLogs(%s): %w", id, err)
	}
	// TODO: inject LogRepository; query by account_id / opts.Type / opts.Page / opts.PageSize
	return []interface{}{}, 0, nil
}

// GetCampaigns returns campaigns that used this account.
func (m *Manager) GetCampaigns(ctx context.Context, id string) ([]interface{}, error) {
	if _, err := m.repo.GetByID(ctx, id); err != nil {
		return nil, fmt.Errorf("account.GetCampaigns(%s): %w", id, err)
	}
	// TODO: inject CampaignRepository; filter by account_ids column
	return []interface{}{}, nil
}

// ImportFromFile bulk-creates accounts from CSV or JSON.
func (m *Manager) ImportFromFile(ctx context.Context, data []byte, ext string) (*ImportResult, error) {
	result := &ImportResult{Errors: []string{}}
	// TODO: parse rows by ext, call m.Create per row, accumulate errors
	return result, nil
}

// ─── Private helpers ─────────────────────────────────────────────────────────

// toModel maps the flat repository.Account to the richer models.Account.
// Key invariant: DB healthscore is 0–1; all exported types use 0–100.
func toModel(ra *repository.Account) *models.Account {
	acc := &models.Account{
		ID:        ra.ID, // string after Fix A
		Email:     ra.Email,
		Name:      ra.Name,
		Provider:  models.Provider(ra.Provider),
		Status:    models.AccountStatus(ra.Status),
		Priority:  ra.Priority,
		CreatedAt: ra.CreatedAt,
		UpdatedAt: ra.UpdatedAt,
		CreatedBy: ra.CreatedBy,
		UpdatedBy: ra.UpdatedBy,
		Limits: models.AccountLimits{
			DailyLimit:        ra.DailyLimit,
			RotationLimit:     ra.RotationLimit,
			SentToday:         int64(ra.SentToday),
			SentSinceRotation: int64(ra.SentThisRotation),
			RemainingDaily:    int64(clampMin(ra.DailyLimit-ra.SentToday, 0)),
		},
		Stats: models.AccountStats{
			TotalSent:   ra.TotalSent,
			TotalFailed: ra.TotalFailed,
		},
		HealthMetrics: models.AccountHealth{
			HealthScore:         ra.HealthScore * 100, // 0–1 → 0–100
			IsHealthy:           ra.HealthScore >= 0.7,
			ConsecutiveFailures: ra.ConsecutiveFailures,
			SuccessRate:         ra.SuccessRate,
		},
		// FIX: ra fields are *time.Time — assign directly, never take &
		LastUsedAt:    ra.LastUsedAt,
		CooldownUntil: ra.CooldownUntil,
	}

	// SMTP — only populate when a host is actually configured
	if ra.SMTPHost != "" {
		acc.SMTPConfig = &models.SMTPConfig{
			Host:   ra.SMTPHost,
			Port:   ra.SMTPPort,
			UseTLS: ra.SMTPUseTLS,
			UseSSL: ra.SMTPUseSSL,
		}
	}
if len(ra.EncryptedPassword) > 0 || ra.OAuthToken != "" { 
		acc.Credentials = &models.AccountCredentials{
			Password:     string(ra.EncryptedPassword),
			AccessToken:  ra.OAuthToken,
			RefreshToken: ra.OAuthRefreshToken,
			IsEncrypted:  len(ra.EncryptedPassword) > 0,
		}
		if ra.OAuthExpiry != nil {
			acc.Credentials.TokenExpiry = ra.OAuthExpiry
		}
	}

	// Suspension — only populate when actually suspended
	if ra.IsSuspended {
		// FIX: models.SuspensionInfo.SuspendedAt is time.Time but ra.SuspendedAt
		//      is *time.Time — dereference safely
		var suspendedAt time.Time
		if ra.SuspendedAt != nil {
			suspendedAt = *ra.SuspendedAt
		}
		acc.SuspensionInfo = &models.SuspensionInfo{
			SuspendedAt:      suspendedAt,
			SuspensionReason: ra.SuspensionReason,
			IsAutoSuspended:  ra.AutoSuspend,
			CanResume:        true,
		}
	}

	return acc
}

// healthStatusLabel converts a 0–100 score to a label.
func healthStatusLabel(score float64) string {
	switch {
	case score >= 90:
		return "healthy"
	case score >= 70:
		return "warning"
	default:
		return "unhealthy"
	}
}

// clampMin returns v unless v < minimum, in which case it returns minimum.
func clampMin(v, minimum int) int {
	if v < minimum {
		return minimum
	}
	return v
}
