package main

import (
	"bytes"
	"crypto/tls"
	"encoding/base64"
	"fmt"
	"log"
	"net/smtp"
	"os"
	"strings"

	"github.com/signintech/gopdf"
)

func main() {
	smtpHost := os.Getenv("SMTP_HOST")
	smtpPort := os.Getenv("SMTP_PORT")
	smtpUser := os.Getenv("SMTP_USER")
	smtpPass := os.Getenv("SMTP_PASS")
	fromName := os.Getenv("FROM_NAME")
	toEmail := os.Getenv("TO_EMAIL")

	if smtpHost == "" || smtpUser == "" || smtpPass == "" || toEmail == "" {
		log.Fatal("Required env vars: SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, TO_EMAIL\n" +
			"Example: SMTP_HOST=smtp.mail.yahoo.com SMTP_PORT=587 SMTP_USER=you@yahoo.com SMTP_PASS=apppass FROM_NAME=TestSender TO_EMAIL=target@gmail.com go run ./cmd/debugsend/")
	}
	if smtpPort == "" {
		smtpPort = "587"
	}
	if fromName == "" {
		fromName = "Debug Sender"
	}

	log.Println("[1/4] Generating test PDF with gopdf...")
	pdfData, err := generateTestPDF()
	if err != nil {
		log.Fatalf("Failed to generate PDF: %v", err)
	}
	log.Printf("[1/4] PDF generated: %d bytes", len(pdfData))

	log.Println("[2/4] Building MIME message with attachment...")
	mime := buildMIMEWithAttachment(smtpUser, fromName, toEmail, "Debug Test - PDF Attachment", pdfData)
	log.Printf("[2/4] MIME message built: %d bytes total", len(mime))

	log.Printf("[3/4] Connecting to SMTP %s:%s ...", smtpHost, smtpPort)
	err = sendViaSMTP(smtpHost, smtpPort, smtpUser, smtpPass, toEmail, mime)
	if err != nil {
		log.Fatalf("SMTP send failed: %v", err)
	}

	log.Println("[4/4] Email sent successfully with PDF attachment!")
	log.Printf("  From: %s <%s>", fromName, smtpUser)
	log.Printf("  To: %s", toEmail)
	log.Printf("  Attachment: test_document.pdf (%d bytes)", len(pdfData))
}

func generateTestPDF() ([]byte, error) {
	pdf := gopdf.GoPdf{}
	pdf.Start(gopdf.Config{PageSize: *gopdf.PageSizeA4})
	pdf.AddPage()

	if err := pdf.AddTTFFont("helvetica", "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"); err != nil {
		pdf.AddTTFFont("helvetica", "/usr/share/fonts/TTF/DejaVuSans.ttf")
	}
	pdf.SetFont("helvetica", "", 24)
	pdf.SetXY(50, 100)
	pdf.Text("Debug Test Document")

	pdf.SetFont("helvetica", "", 14)
	pdf.SetXY(50, 160)
	pdf.Text("This PDF was generated by gopdf to test")
	pdf.SetXY(50, 185)
	pdf.Text("that SMTP attachment sending works correctly.")
	pdf.SetXY(50, 230)
	pdf.Text("If you see this file attached to the email,")
	pdf.SetXY(50, 255)
	pdf.Text("the attachment pipeline is working end-to-end.")

	pdf.SetFont("helvetica", "", 10)
	pdf.SetXY(50, 320)
	pdf.Text("Generated by Ghost-Sender debug tool")

	var buf bytes.Buffer
	_, err := pdf.WriteTo(&buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func buildMIMEWithAttachment(from, fromName, to, subject string, pdfData []byte) []byte {
	boundary := "----=_DebugTest_Boundary_12345"

	var msg strings.Builder

	msg.WriteString(fmt.Sprintf("From: %s <%s>\r\n", fromName, from))
	msg.WriteString(fmt.Sprintf("To: <%s>\r\n", to))
	msg.WriteString(fmt.Sprintf("Subject: %s\r\n", subject))
	msg.WriteString("MIME-Version: 1.0\r\n")
	msg.WriteString(fmt.Sprintf("Content-Type: multipart/mixed; boundary=\"%s\"\r\n", boundary))
	msg.WriteString("\r\n")

	msg.WriteString(fmt.Sprintf("--%s\r\n", boundary))
	msg.WriteString("Content-Type: text/html; charset=\"UTF-8\"\r\n")
	msg.WriteString("Content-Transfer-Encoding: quoted-printable\r\n\r\n")
	msg.WriteString("<html><body><h2>Debug Test Email</h2>")
	msg.WriteString("<p>This email should have a PDF attached named <b>test_document.pdf</b>.</p>")
	msg.WriteString("<p>If you see the attachment, SMTP attachment sending works correctly.</p>")
	msg.WriteString("</body></html>\r\n\r\n")

	msg.WriteString(fmt.Sprintf("--%s\r\n", boundary))
	msg.WriteString("Content-Type: application/pdf; name=\"test_document.pdf\"\r\n")
	msg.WriteString("Content-Transfer-Encoding: base64\r\n")
	msg.WriteString("Content-Disposition: attachment; filename=\"test_document.pdf\"\r\n\r\n")

	encoded := base64.StdEncoding.EncodeToString(pdfData)
	for i := 0; i < len(encoded); i += 76 {
		end := i + 76
		if end > len(encoded) {
			end = len(encoded)
		}
		msg.WriteString(encoded[i:end])
		msg.WriteString("\r\n")
	}
	msg.WriteString("\r\n")

	msg.WriteString(fmt.Sprintf("--%s--\r\n", boundary))

	return []byte(msg.String())
}

func sendViaSMTP(host, port, user, pass, to string, message []byte) error {
	addr := fmt.Sprintf("%s:%s", host, port)
	conn, err := smtp.Dial(addr)
	if err != nil {
		return fmt.Errorf("dial failed: %w", err)
	}
	defer conn.Close()

	tlsConfig := &tls.Config{ServerName: host}
	if err := conn.StartTLS(tlsConfig); err != nil {
		return fmt.Errorf("STARTTLS failed: %w", err)
	}

	auth := smtp.PlainAuth("", user, pass, host)
	if err := conn.Auth(auth); err != nil {
		return fmt.Errorf("auth failed: %w", err)
	}

	if err := conn.Mail(user); err != nil {
		return fmt.Errorf("MAIL FROM failed: %w", err)
	}
	if err := conn.Rcpt(to); err != nil {
		return fmt.Errorf("RCPT TO failed: %w", err)
	}

	w, err := conn.Data()
	if err != nil {
		return fmt.Errorf("DATA failed: %w", err)
	}
	_, err = w.Write(message)
	if err != nil {
		return fmt.Errorf("write failed: %w", err)
	}
	if err := w.Close(); err != nil {
		return fmt.Errorf("close failed: %w", err)
	}

	return conn.Quit()
}
