-- Add all missing account columns
ALTER TABLE accounts 
ADD COLUMN IF NOT EXISTS smtp_use_tls BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS smtp_use_ssl BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS smtp_username VARCHAR(255),
ADD COLUMN IF NOT EXISTS oauth_token TEXT,
ADD COLUMN IF NOT EXISTS oauth_refresh_token TEXT,
ADD COLUMN IF NOT EXISTS oauth_expiry TIMESTAMP,
ADD COLUMN IF NOT EXISTS last_used_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS last_success_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS last_failure_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS total_failed INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS success_rate DECIMAL(5,2) DEFAULT 100.0,
ADD COLUMN IF NOT EXISTS cooldown_until TIMESTAMP,
ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
