ALTER TABLE recipients
  ADD COLUMN IF NOT EXISTS is_valid BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS unsubscribed BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS hard_bounced BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS soft_bounced BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS complaint_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sent_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS failed_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS engagement_score NUMERIC NOT NULL DEFAULT 0.0;
